import type { ReactNode } from 'react';
import type { IconSize, IconStroke } from './ui/Icon';

type IconRenderer = (size?: IconSize, opts?: { stroke?: IconStroke }) => ReactNode;

declare const Ico: {
  attach: IconRenderer;
  brain: IconRenderer;
  arrowUpLeft: IconRenderer;
  arrowUpRight: IconRenderer;
  appWindow: IconRenderer;
  check: IconRenderer;
  chevDown: IconRenderer;
  chevLeft: IconRenderer;
  chevRight: IconRenderer;
  clock: IconRenderer;
  close: IconRenderer;
  code: IconRenderer;
  computer: IconRenderer;
  copy: IconRenderer;
  cube: IconRenderer;
  doc: IconRenderer;
  edit: IconRenderer;
  externalLink: IconRenderer;
  folder: IconRenderer;
  globe: IconRenderer;
  grid: IconRenderer;
  image: IconRenderer;
  key: IconRenderer;
  lock: IconRenderer;
  mindsdb: IconRenderer;
  more: IconRenderer;
  moreVert: IconRenderer;
  openFolder: IconRenderer;
  panelExpandLeft: IconRenderer;
  plus: IconRenderer;
  refresh: IconRenderer;
  search: IconRenderer;
  link: IconRenderer;
  list: IconRenderer;
  pin: IconRenderer;
  play: IconRenderer;
  phone: IconRenderer;
  reload: IconRenderer;
  send: IconRenderer;
  settings: IconRenderer;
  slider: IconRenderer;
  stop: IconRenderer;
  taskCheck: IconRenderer;
  trash: IconRenderer;
  user: IconRenderer;
  warning: IconRenderer;
};

export default Ico;
