// Icon keys are also resolved from data: search string references before renaming or removing them.
// Use the shared 1.5 stroke weight. Brand marks and compact solid stop/pause glyphs remain custom.
import {
  AppWindow,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  Bot,
  Box,
  Brain,
  CalendarClock,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CodeXml,
  Copy,
  Database,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Folder,
  FolderInput,
  FolderOpen,
  Gamepad2,
  Globe,
  Image,
  KeyRound,
  LayoutGrid,
  Link,
  List,
  Lock,
  Mail,
  Menu,
  MessagesSquare,
  Mic,
  Monitor,
  Moon,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Play,
  Pin,
  Plus,
  Power,
  PowerOff,
  Presentation,
  RefreshCw,
  RotateCw,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquareCheckBig,
  Sun,
  Table,
  Telescope,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Upload,
  Users,
  Wifi,
  X,
} from 'lucide-react';

// Adapt Lucide components to the existing (size) icon functions; childless Lucide icons supply
// aria-hidden.
const ico = (Cmp, d = 16) => (s = d) => <Cmp size={s} strokeWidth={1.5} />;

const Ico = {
  search:   ico(Search),
  chats:    ico(MessagesSquare),
  list:     ico(List),
  grid:     ico(LayoutGrid),
  image:    ico(Image),
  sidebar:  ico(PanelLeft),
  sidebarCollapseLeft: ico(PanelLeftClose),
  sidebarExpandRight:  ico(PanelLeftOpen),
  panelCollapseRight:  ico(PanelRightClose),
  panelExpandLeft:     ico(PanelRightOpen),
  menu:     ico(Menu),
  sun:      ico(Sun),
  moon:     ico(Moon),
  gamepad:  ico(Gamepad2),
  palette:  ico(Palette),
  power:    ico(Power),
  powerOff: ico(PowerOff),
  copy:     ico(Copy),
  refresh:  ico(RotateCw),
  thumbUp:  ico(ThumbsUp),
  thumbDown: ico(ThumbsDown),
  chevronRight: ico(ChevronRight),
  code:     ico(CodeXml),
  plus:     ico(Plus),
  folder:   ico(Folder),
  computer: ico(Monitor),
  phone:    ico(Smartphone),
  clock:    ico(Clock),
  sparkle:  ico(Sparkles),
  slider:   ico(SlidersHorizontal),
  settings: ico(Settings),
  pin:      ico(Pin),
  play:     ico(Play),
  chevDown: ico(ChevronDown, 14),
  chevRight: ico(ChevronRight, 14),
  chevLeft: ico(ChevronLeft, 14),
  mic:      ico(Mic),
  send:     ico(ArrowUp),
  attach:   ico(Paperclip),
  download: ico(Download),
  check:    ico(Check, 14),
  taskCheck: ico(SquareCheckBig),
  more:     ico(Ellipsis),
  moreVert: ico(EllipsisVertical),
  edit:     ico(Pencil),
  trash:    ico(Trash2),
  moveTo:   ico(FolderInput),
  schedule: ico(CalendarClock),
  doc:      ico(FileText),
  globe:    ico(Globe),
  brain:    ico(Brain),
  database: ico(Database),
  mail:     ico(Mail),
  upload:   ico(Upload),
  wifi:     ico(Wifi),
  key:      ico(KeyRound),
  lock:     ico(Lock),
  people:   ico(Users),
  robot:    ico(Bot),
  link:     ico(Link),
  cube:     ico(Box),
  externalLink: ico(ExternalLink, 14),
  close:    ico(X, 14),
  eye:      ico(Eye, 14),
  eyeOff:   ico(EyeOff, 14),
  openFolder:   ico(FolderOpen),
  reload:       ico(RefreshCw),
  arrowUpRight: ico(ArrowUpRight),
  arrowUpLeft: ico(ArrowUpLeft, 14),
  presentation: ico(Presentation),
  appWindow:    ico(AppWindow),
  table:        ico(Table),
  chartColumn:  ico(ChartColumn),
  telescope:    ico(Telescope),
  // Matches the mdb-ai adapter’s step.icon value.
  save:     ico(Save),

  // Brand icons absent from Lucide; Google Drive uses public/logos/google_drive.svg geometry with a
  // monochrome currentColor fill.
  googleDrive: (s = 16) => <svg width={s} height={s} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12.01 1.485c-2.082 0-3.754.02-3.743.047.01.02 1.708 3.001 3.774 6.62l3.76 6.574h3.76c2.081 0 3.753-.02 3.742-.047-.005-.02-1.708-3.001-3.775-6.62l-3.76-6.574zm-4.76 1.73a789.828 789.861 0 0 0-3.63 6.319L0 15.868l1.89 3.298 1.885 3.297 3.62-6.335 3.618-6.33-1.88-3.287C8.1 4.704 7.255 3.22 7.25 3.214zm2.259 12.653-.203.348c-.114.198-.96 1.672-1.88 3.287a423.93 423.948 0 0 1-1.698 2.97c-.01.026 3.24.042 7.222.042h7.244l1.796-3.157c.992-1.734 1.85-3.23 1.906-3.323l.104-.167h-7.249z"/></svg>,
  mindsdb:  (s = 14) => <svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" aria-hidden="true"><path d="M3 17v3h3M21 7V4h-3M3 7V4h3M21 17v3h-3"/><circle cx="12" cy="12" r="4"/></svg>,
  // Use smaller solid glyphs than Lucide’s full-grid Square/Pause.
  stop:     (s = 16) => <svg width={s} height={s} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2"/></svg>,
  pause:    (s = 16) => <svg width={s} height={s} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6" y="5" width="4" height="14" rx="1"/><rect x="14" y="5" width="4" height="14" rx="1"/></svg>,
};

export default Ico;
