"""
Artifacts — files generated by Anton and stored in .anton/output/.
Scans all registered projects for output files.
"""
from __future__ import annotations

import hashlib
import json
import logging
import mimetypes
import subprocess
import time
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse
from pydantic import BaseModel

from anton_api import projects_store

router = APIRouter()
logger = logging.getLogger(__name__)

# In-memory registry mapping a short, deterministic token to the parent
# directory of an HTML artifact. Used by the in-app iframe preview so
# relative `<script src=…>` / `<link href=…>` references can resolve
# against a real URL (srcdoc has no base URL → relative refs 404).
# The token is sha256(parent_dir)[:16] — stable across calls so reopens
# don't allocate fresh entries.
_PREVIEW_MOUNTS: dict[str, Path] = {}

KIND_MAP = {
    ".html": "Dashboard",
    ".md":   "Document",
    ".txt":  "Document",
    ".csv":  "Spreadsheet",
    ".json": "Data",
    ".py":   "Code",
    ".js":   "Code",
    ".png":  "Image",
    ".jpg":  "Image",
    ".jpeg": "Image",
    ".svg":  "Image",
    ".pdf":  "PDF",
}

BG_CYCLE = [
    "linear-gradient(135deg, var(--stone-100), var(--surface-03))",
    "linear-gradient(135deg, var(--ocean-50), #fff)",
    "linear-gradient(135deg, var(--sage-50), #fff)",
    "linear-gradient(135deg, #fff, var(--stone-150))",
]


def _human_mtime(path: Path) -> str:
    secs = time.time() - path.stat().st_mtime
    if secs < 60:      return "updated just now"
    if secs < 3600:    return f"updated {int(secs // 60)}m ago"
    if secs < 86400:   return f"updated {int(secs // 3600)}h ago"
    return f"updated {int(secs // 86400)}d ago"


def _snippet(path: Path) -> str:
    try:
        if path.suffix in (".html", ".md", ".txt", ".csv"):
            text = path.read_text(encoding="utf-8", errors="replace")
            lines = [l for l in text.splitlines() if l.strip()][:6]
            return "\n".join(lines)[:200]
    except Exception:
        pass
    return ""


def _scan_output_dirs() -> list[Path]:
    dirs: dict[str, Path] = {}
    global_output = Path.home() / ".anton" / "output"
    if global_output.is_dir():
        dirs[str(global_output.resolve())] = global_output
    for project in projects_store.list_projects():
        output_dir = Path(project["path"]) / ".anton" / "output"
        if output_dir.is_dir():
            dirs[str(output_dir.resolve())] = output_dir
    return list(dirs.values())


def _resolve_artifact_path(raw_path: str) -> Path:
    try:
        target = Path(raw_path).expanduser().resolve()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid artifact path") from exc

    for output_dir in _scan_output_dirs():
        try:
            output_root = output_dir.resolve()
            target.relative_to(output_root)
            if target.is_file():
                return target
        except ValueError:
            continue
    raise HTTPException(status_code=404, detail="Artifact is not in a known Anton output directory")


TEXT_EXTENSIONS = {".html", ".md", ".txt", ".csv", ".json", ".py", ".js", ".ts", ".tsx", ".css", ".log"}


@router.get("")
async def list_artifacts():
    artifacts = []
    seen = set()
    files: list[Path] = []

    for output_dir in _scan_output_dirs():
        if not output_dir.exists():
            continue
        try:
            files.extend(path for path in output_dir.rglob("*") if path.is_file() and not path.name.startswith("."))
        except Exception:
            continue

    try:
        files = sorted(files, key=lambda p: p.stat().st_mtime, reverse=True)
    except Exception:
        pass

    for f in files:
        key = str(f)
        if key in seen:
            continue
        seen.add(key)

        ext = f.suffix.lower()
        kind = KIND_MAP.get(ext, "File")
        is_live = (time.time() - f.stat().st_mtime) < 300  # "live" if modified in last 5 min
        idx = len(artifacts) % len(BG_CYCLE)

        # For HTML artifacts, surface the published URL (if any) so the
        # client can show a "Published" pill without a second round-trip.
        published_url = ""
        if ext == ".html":
            published_path = f.parent / ".published.json"
            if published_path.is_file():
                try:
                    pmap = json.loads(published_path.read_text(encoding="utf-8"))
                    entry = pmap.get(f.name)
                    if isinstance(entry, dict):
                        published_url = entry.get("url", "") or ""
                except Exception:
                    pass

        artifacts.append({
            "id": f.stem + "_" + str(int(f.stat().st_mtime)),
            "title": f.stem.replace("_", " ").replace("-", " ").title(),
            "kind": kind,
            "ext": ext,
            "updated": _human_mtime(f),
            "live": is_live,
            "bg": BG_CYCLE[idx],
            "snippet": _snippet(f),
            "path": str(f),
            "publishedUrl": published_url,
        })

        if len(artifacts) >= 40:
            break

    return artifacts


@router.get("/preview")
async def preview_artifact(path: str = Query(...)):
    artifact = _resolve_artifact_path(path)
    suffix = artifact.suffix.lower()
    if suffix not in TEXT_EXTENSIONS:
        raise HTTPException(status_code=415, detail="Preview is available for text, Markdown, code, JSON, CSV, and HTML files")
    try:
        text = artifact.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Could not read artifact") from exc

    return {
        "path": str(artifact),
        "title": artifact.name,
        "kind": KIND_MAP.get(suffix, "File"),
        "mime": mimetypes.guess_type(str(artifact))[0] or "text/plain",
        "content": text[:200_000],
        "truncated": len(text) > 200_000,
    }


# ─── Iframe preview mount ────────────────────────────────────────────────
#
# Two-step flow used by ArtifactViewer to render HTML with relative asset
# references intact:
#
#   1. POST /v1/artifacts/preview-mount {path} → register the artifact's
#      parent dir under a deterministic token, return the entry filename
#      and a relative URL the iframe should load.
#   2. GET  /v1/artifacts/preview-asset/{token}/{rel_path}  → serve files
#      from that mounted dir, restricted to descendants of the parent so
#      a malicious artifact can't traverse into the rest of the disk.
#
# The iframe loads the entry URL with `src=` (not srcdoc), so the
# browser resolves relative refs against the asset URL — `chart.js`,
# `style.css`, sibling images, etc. all load correctly.

class PreviewMountRequest(BaseModel):
    path: str


@router.post("/preview-mount")
async def preview_mount(req: PreviewMountRequest):
    artifact = _resolve_artifact_path(req.path)
    if artifact.suffix.lower() != ".html":
        raise HTTPException(status_code=415, detail="Preview mount is only available for HTML artifacts")
    parent = artifact.parent.resolve()
    # Stable per-parent. No TTL — the registry naturally caps at a few
    # entries since each project has at most one .anton/output dir.
    token = hashlib.sha256(str(parent).encode("utf-8")).hexdigest()[:16]
    _PREVIEW_MOUNTS[token] = parent
    return {
        "token": token,
        "entry": artifact.name,
        # Relative path the client can append to BASE; full URL is built
        # client-side so we don't need to know the host here.
        "relUrl": f"/artifacts/preview-asset/{token}/{artifact.name}",
    }


@router.get("/preview-asset/{token}/{rel_path:path}")
async def preview_asset(token: str, rel_path: str):
    parent = _PREVIEW_MOUNTS.get(token)
    if parent is None:
        raise HTTPException(status_code=404, detail="Preview mount has expired or is unknown")
    try:
        target = (parent / rel_path).resolve()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid asset path") from exc
    # Path-traversal guard — the resolved target must remain inside
    # the mounted parent directory.
    try:
        target.relative_to(parent)
    except ValueError:
        raise HTTPException(status_code=403, detail="Asset is outside the artifact directory")
    if not target.is_file():
        raise HTTPException(status_code=404, detail="Asset not found")
    media_type = mimetypes.guess_type(str(target))[0] or "application/octet-stream"
    # Cache aggressively for assets — they're keyed by token (which is
    # derived from the parent dir) and we expect them to be immutable
    # for the life of the artifact. Browsers will revalidate on hard
    # refresh anyway.
    return FileResponse(target, media_type=media_type, headers={
        "Cache-Control": "private, max-age=300",
    })


class ArtifactAction(BaseModel):
    path: str


@router.post("/open")
async def open_artifact(req: ArtifactAction):
    artifact = _resolve_artifact_path(req.path)
    try:
        subprocess.run(["open", str(artifact)], check=False)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Could not open artifact") from exc
    return {"status": "ok", "path": str(artifact)}


@router.post("/reveal")
async def reveal_artifact(req: ArtifactAction):
    artifact = _resolve_artifact_path(req.path)
    try:
        subprocess.run(["open", "-R", str(artifact)], check=False)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Could not reveal artifact") from exc
    return {"status": "ok", "path": str(artifact)}
