"""
Artifacts — files generated by Anton and stored in .anton/output/.
Scans all registered projects for output files.
"""
from __future__ import annotations

import hashlib
import json
import logging
import mimetypes
import subprocess
import sys
import time
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse
from pydantic import BaseModel

from anton_api import projects_store

router = APIRouter()
logger = logging.getLogger(__name__)

# In-memory registry mapping a short, deterministic token to the parent
# directory of an HTML artifact. Used by the in-app iframe preview so
# relative `<script src=…>` / `<link href=…>` references can resolve
# against a real URL (srcdoc has no base URL → relative refs 404).
# The token is sha256(parent_dir)[:16] — stable across calls so reopens
# don't allocate fresh entries.
_PREVIEW_MOUNTS: dict[str, Path] = {}

KIND_MAP = {
    ".html": "Dashboard",
    ".md":   "Document",
    ".txt":  "Document",
    ".csv":  "Spreadsheet",
    ".json": "Data",
    ".py":   "Code",
    ".js":   "Code",
    ".png":  "Image",
    ".jpg":  "Image",
    ".jpeg": "Image",
    ".svg":  "Image",
    ".pdf":  "PDF",
}

BG_CYCLE = [
    "linear-gradient(135deg, var(--stone-100), var(--surface-03))",
    "linear-gradient(135deg, var(--ocean-50), #fff)",
    "linear-gradient(135deg, var(--sage-50), #fff)",
    "linear-gradient(135deg, #fff, var(--stone-150))",
]


def _human_mtime(path: Path) -> str:
    secs = time.time() - path.stat().st_mtime
    if secs < 60:      return "updated just now"
    if secs < 3600:    return f"updated {int(secs // 60)}m ago"
    if secs < 86400:   return f"updated {int(secs // 3600)}h ago"
    return f"updated {int(secs // 86400)}d ago"


def _snippet(path: Path) -> str:
    try:
        if path.suffix in (".html", ".md", ".txt", ".csv"):
            text = path.read_text(encoding="utf-8", errors="replace")
            lines = [l for l in text.splitlines() if l.strip()][:6]
            return "\n".join(lines)[:200]
    except Exception:
        pass
    return ""


def _scan_output_dirs() -> list[Path]:
    """Directories to walk when listing or resolving artifacts.

    The historical pair was `~/.anton/output/` + `<project>/.anton/output/`,
    but anton's actual save behaviour is fuzzier:
      - Some `output_context` system prompts told the LLM to "save in
        the project directory" without specifying `.anton/output/`.
      - `pad.execute_streaming` runs with cwd = workspace root, so any
        `with open(...)` in scratchpad code that uses a bare relative
        filename lands in the workspace root.
      - The LLM occasionally invents folders like `dashboards/`,
        `outputs/`, `reports/`.
    All those land outside the original two roots, the artifact list
    silently skipped them, and clicking a card returned 404 from
    `_resolve_artifact_path`.

    The expansion below adds the project workspace ROOT as a scan
    target. The list-view uses `ARTIFACT_EXTENSIONS` to keep
    user-typed `.py` / `requirements.txt` / etc. out of the artifact
    list; the resolve path accepts anything under the workspace so a
    direct click on a non-listed file (e.g. an `.ipynb`) still opens.
    """
    dirs: dict[str, Path] = {}
    global_output = Path.home() / ".anton" / "output"
    if global_output.is_dir():
        dirs[str(global_output.resolve())] = global_output
    for project in projects_store.list_projects():
        output_dir = Path(project["path"]) / ".anton" / "output"
        if output_dir.is_dir():
            dirs[str(output_dir.resolve())] = output_dir
    return list(dirs.values())


def _scan_workspace_roots() -> list[Path]:
    """Project workspace roots — the broader search domain.

    Used for the list-view's secondary pass (extension-filtered) and
    the resolve-path validator. Returned in the same shape as
    `_scan_output_dirs` so the listing loop can iterate both.
    """
    out: dict[str, Path] = {}
    for project in projects_store.list_projects():
        path = Path(project["path"])
        if path.is_dir():
            out[str(path.resolve())] = path
    return list(out.values())


# Files we surface in the artifacts LIST view. Tighter than what
# we'll OPEN — `.py` and `.txt` source files aren't user-facing
# artifacts, but `_resolve_artifact_path` will still open them if a
# caller links directly. Keep this in sync with `KIND_MAP` above.
ARTIFACT_EXTENSIONS = {
    ".html", ".md", ".pdf", ".csv", ".json",
    ".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp",
}

# Workspace-root scan ignores these directories outright. Walking
# `node_modules/` etc. would be ruinous; users don't think of them
# as artifact homes. `.anton/` is excluded only at the workspace-
# root layer because we already scan `.anton/output/` directly via
# `_scan_output_dirs` and the rest of `.anton/` (episodes, memory,
# context) is internal bookkeeping.
WORKSPACE_SCAN_IGNORES = {
    ".anton", ".context",
    ".git", ".hg", ".svn",
    "node_modules", ".venv", "venv", "env", ".env",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "dist", "build", "out",
    ".next", ".turbo", ".cache",
}


def _walk_workspace_root(root: Path):
    """Walk a workspace root, skipping ignored dirs. Yields files."""
    if not root.is_dir():
        return
    try:
        stack = [root]
        while stack:
            cur = stack.pop()
            try:
                entries = list(cur.iterdir())
            except (OSError, PermissionError):
                continue
            for entry in entries:
                name = entry.name
                if name.startswith("."):
                    # Hidden files / dirs at any depth — skip. The
                    # global `~/.anton/output/` is reached via
                    # `_scan_output_dirs`, not via this walker.
                    continue
                if entry.is_dir():
                    if name in WORKSPACE_SCAN_IGNORES:
                        continue
                    stack.append(entry)
                elif entry.is_file():
                    yield entry
    except Exception:
        return


def _candidate_relative_artifacts(raw_path: str) -> list[Path]:
    text = (raw_path or "").strip().replace("\\", "/")
    while text.startswith("./"):
        text = text[2:]
    parts = [part for part in text.split("/") if part]
    if not text or any(part in (".", "..") for part in parts):
        raise HTTPException(status_code=400, detail="Invalid artifact path")

    rels: list[str]
    if text.startswith(".anton/output/"):
        rels = [text[len(".anton/output/"):]]
    elif text.startswith("anton/output/"):
        # Compatibility shim for streamed display paths that omit the
        # leading dot. Artifacts still live under `.anton/output`.
        rels = [text[len("anton/output/"):]]
    else:
        rels = [text]

    matches: dict[str, Path] = {}
    for output_dir in _scan_output_dirs():
        output_root = output_dir.resolve()
        for rel in rels:
            try:
                target = (output_root / rel).resolve()
                target.relative_to(output_root)
            except ValueError:
                continue
            if target.is_file():
                matches[str(target)] = target
    return list(matches.values())


def _resolve_artifact_path(raw_path: str) -> Path:
    """Resolve a request to an absolute artifact path on disk.

    Accepted locations (in priority order):
      1. The classic Anton output dirs (`~/.anton/output/`,
         `<project>/.anton/output/`) — strict, unchanged.
      2. Anywhere under any registered project's workspace root —
         loosened so `dashboards/q4.html` or a workspace-root
         `report.html` opens cleanly. Hidden / ignore-listed dirs
         (`.anton/`, `node_modules/`, `.venv/`, …) are excluded so a
         scoped path can't escape the project tree.
    """
    try:
        target = Path(raw_path).expanduser()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid artifact path") from exc

    if not str(target).strip():
        raise HTTPException(status_code=400, detail="Invalid artifact path")

    if target.is_absolute():
        resolved = target.resolve()
        # Tier 1 — classic output dirs.
        for output_dir in _scan_output_dirs():
            try:
                output_root = output_dir.resolve()
                resolved.relative_to(output_root)
                if resolved.is_file():
                    return resolved
            except ValueError:
                continue
        # Tier 2 — anywhere under a project workspace, minus the
        # ignore list. We check that NO segment of the path under the
        # project root falls in WORKSPACE_SCAN_IGNORES.
        for ws_root in _scan_workspace_roots():
            try:
                ws = ws_root.resolve()
                rel = resolved.relative_to(ws)
            except ValueError:
                continue
            if not resolved.is_file():
                continue
            parts = rel.parts
            # Reject hidden segments anywhere in the relative path,
            # except for `.anton/output/` which is permitted since
            # that's the canonical artifact home.
            forbidden_hidden = False
            for seg in parts[:-1]:
                if seg.startswith(".") and seg != ".anton":
                    forbidden_hidden = True
                    break
                if seg in WORKSPACE_SCAN_IGNORES:
                    # `.anton/output/` is fine; anything else under
                    # `.anton/` (episodes, memory, context) is not.
                    if seg == ".anton" and len(parts) >= 2 and parts[1] == "output":
                        continue
                    forbidden_hidden = True
                    break
            if forbidden_hidden:
                continue
            return resolved
        raise HTTPException(status_code=404, detail="Artifact is not in a known Anton output directory")

    matches = _candidate_relative_artifacts(raw_path)
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        raise HTTPException(
            status_code=400,
            detail="Artifact path matches multiple Anton output directories; use an absolute path",
        )
    raise HTTPException(status_code=404, detail="Artifact is not in a known Anton output directory")


def _reveal_in_file_manager(artifact: Path) -> None:
    if sys.platform == "darwin":
        subprocess.run(["open", "-R", str(artifact)], check=False)
    elif sys.platform == "win32":
        subprocess.run(["explorer", f"/select,{artifact}"], check=False)
    else:
        subprocess.run(["xdg-open", str(artifact.parent)], check=False)


TEXT_EXTENSIONS = {".html", ".md", ".txt", ".csv", ".json", ".py", ".js", ".ts", ".tsx", ".css", ".log"}


@router.get("")
async def list_artifacts():
    artifacts = []
    seen: set[str] = set()
    files: list[Path] = []

    # Tier 1 — `.anton/output/` dirs. Anything in here is considered
    # an artifact regardless of extension (it's a curated location).
    for output_dir in _scan_output_dirs():
        if not output_dir.exists():
            continue
        try:
            for path in output_dir.rglob("*"):
                if not path.is_file() or path.name.startswith("."):
                    continue
                key = str(path.resolve())
                if key in seen:
                    continue
                seen.add(key)
                files.append(path)
        except Exception:
            continue

    # Tier 2 — workspace roots, filtered by ARTIFACT_EXTENSIONS so
    # we don't surface every `.py` source file as an artifact card.
    # Keeps the list focused on user-facing outputs (HTML dashboards,
    # CSVs, PDFs, images, JSON data) wherever the LLM saved them.
    for ws_root in _scan_workspace_roots():
        for path in _walk_workspace_root(ws_root):
            if path.suffix.lower() not in ARTIFACT_EXTENSIONS:
                continue
            key = str(path.resolve())
            if key in seen:
                continue
            seen.add(key)
            files.append(path)

    try:
        files = sorted(files, key=lambda p: p.stat().st_mtime, reverse=True)
    except Exception:
        pass

    for f in files:
        ext = f.suffix.lower()
        kind = KIND_MAP.get(ext, "File")
        is_live = (time.time() - f.stat().st_mtime) < 300  # "live" if modified in last 5 min
        idx = len(artifacts) % len(BG_CYCLE)

        # For HTML artifacts, surface the published URL (if any) so the
        # client can show a "Published" pill without a second round-trip.
        published_url = ""
        if ext == ".html":
            published_path = f.parent / ".published.json"
            if published_path.is_file():
                try:
                    pmap = json.loads(published_path.read_text(encoding="utf-8"))
                    entry = pmap.get(f.name)
                    if isinstance(entry, dict):
                        published_url = entry.get("url", "") or ""
                except Exception:
                    pass

        artifacts.append({
            "id": f.stem + "_" + str(int(f.stat().st_mtime)),
            "title": f.stem.replace("_", " ").replace("-", " ").title(),
            "kind": kind,
            "ext": ext,
            "updated": _human_mtime(f),
            "live": is_live,
            "bg": BG_CYCLE[idx],
            "snippet": _snippet(f),
            "path": str(f),
            "publishedUrl": published_url,
        })

        if len(artifacts) >= 40:
            break

    return artifacts


@router.get("/preview")
async def preview_artifact(path: str = Query(...)):
    artifact = _resolve_artifact_path(path)
    suffix = artifact.suffix.lower()
    if suffix not in TEXT_EXTENSIONS:
        raise HTTPException(status_code=415, detail="Preview is available for text, Markdown, code, JSON, CSV, and HTML files")
    try:
        text = artifact.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Could not read artifact") from exc

    return {
        "path": str(artifact),
        "title": artifact.name,
        "kind": KIND_MAP.get(suffix, "File"),
        "mime": mimetypes.guess_type(str(artifact))[0] or "text/plain",
        "content": text[:200_000],
        "truncated": len(text) > 200_000,
    }


# ─── Iframe preview mount ────────────────────────────────────────────────
#
# Two-step flow used by ArtifactViewer to render HTML with relative asset
# references intact:
#
#   1. POST /v1/artifacts/preview-mount {path} → register the artifact's
#      parent dir under a deterministic token, return the entry filename
#      and a relative URL the iframe should load.
#   2. GET  /v1/artifacts/preview-asset/{token}/{rel_path}  → serve files
#      from that mounted dir, restricted to descendants of the parent so
#      a malicious artifact can't traverse into the rest of the disk.
#
# The iframe loads the entry URL with `src=` (not srcdoc), so the
# browser resolves relative refs against the asset URL — `chart.js`,
# `style.css`, sibling images, etc. all load correctly.

class PreviewMountRequest(BaseModel):
    path: str


@router.post("/preview-mount")
async def preview_mount(req: PreviewMountRequest):
    artifact = _resolve_artifact_path(req.path)
    if artifact.suffix.lower() != ".html":
        raise HTTPException(status_code=415, detail="Preview mount is only available for HTML artifacts")
    parent = artifact.parent.resolve()
    # Stable per-parent. No TTL — the registry naturally caps at a few
    # entries since each project has at most one .anton/output dir.
    token = hashlib.sha256(str(parent).encode("utf-8")).hexdigest()[:16]
    _PREVIEW_MOUNTS[token] = parent

    # Surface the published URL alongside the mount info so the viewer
    # shows the "Published" pill regardless of how it was opened. The
    # `/artifacts` list endpoint already enriches its rows the same
    # way; the in-chat / project surfaces build their artifact object
    # from streamed scratchpad payloads which never carry it, so the
    # sidecar lookup has to happen here too.
    published_url = ""
    published_path = parent / ".published.json"
    if published_path.is_file():
        try:
            pmap = json.loads(published_path.read_text(encoding="utf-8"))
            entry = pmap.get(artifact.name)
            if isinstance(entry, dict):
                published_url = entry.get("url", "") or ""
        except Exception:
            published_url = ""

    return {
        "token": token,
        "entry": artifact.name,
        # Relative path the client can append to BASE; full URL is built
        # client-side so we don't need to know the host here.
        "relUrl": f"/artifacts/preview-asset/{token}/{artifact.name}",
        "publishedUrl": published_url,
    }


@router.get("/preview-asset/{token}/{rel_path:path}")
async def preview_asset(token: str, rel_path: str):
    parent = _PREVIEW_MOUNTS.get(token)
    if parent is None:
        raise HTTPException(status_code=404, detail="Preview mount has expired or is unknown")
    parent_resolved = parent.resolve()
    try:
        target = (parent / rel_path).resolve()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid asset path") from exc
    # Path-traversal guard — the resolved target must remain inside the
    # mounted parent directory. `is_relative_to` is the canonical
    # sanitizer form recognised by Snyk Code (CWE-23) and CodeQL
    # (py/path-injection); kept as the gate immediately preceding any
    # filesystem access on `target`.
    if not target.is_relative_to(parent_resolved):
        raise HTTPException(status_code=403, detail="Asset is outside the artifact directory")
    if not target.is_file():
        raise HTTPException(status_code=404, detail="Asset not found")
    media_type = mimetypes.guess_type(str(target))[0] or "application/octet-stream"
    # Cache aggressively for assets — they're keyed by token (which is
    # derived from the parent dir) and we expect them to be immutable
    # for the life of the artifact. Browsers will revalidate on hard
    # refresh anyway.
    return FileResponse(target, media_type=media_type, headers={
        "Cache-Control": "private, max-age=300",
    })


class ArtifactAction(BaseModel):
    path: str


@router.post("/open")
async def open_artifact(req: ArtifactAction):
    artifact = _resolve_artifact_path(req.path)
    try:
        subprocess.run(["open", str(artifact)], check=False)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Could not open artifact") from exc
    return {"status": "ok", "path": str(artifact)}


@router.post("/reveal")
async def reveal_artifact(req: ArtifactAction):
    artifact = _resolve_artifact_path(req.path)
    try:
        _reveal_in_file_manager(artifact)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Could not reveal artifact") from exc
    return {"status": "ok", "path": str(artifact)}
