deployment:
  ingress:
    enabled: true
    name: cowork-frontend
    pathType: Prefix
    hosts:
      - host: cowork.staging.mindshub.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: cowork-frontend
            servicePort: 80
