// Shared types for the embedded browser feature (see CLAUDE.md §Embedded
// browser). Wire protocol between renderer, main, and the loopback agent
// bridge — treat renames as breaking changes, same as the IPC channel strings.

export interface BrowserTabInfo {
  id: string;                 // nanoid-style, generated by main
  title: string;              // '' while blank
  url: string;                // '' = blank start-page tab
  favicon: string | null;     // data: or https: URL
  pinned: boolean;            // pinned tabs lead the strip and can't be closed
  zoom?: number;              // per-tab zoom factor (default 1; additive)
  isLoading: boolean;
  loadProgress: number;       // 0..1
  canGoBack: boolean;
  canGoForward: boolean;
  error: { code: number; description: string } | null;
  isAgentControlled: boolean; // true while the bridge last drove this tab (recent window)
}

export interface BrowserState {
  tabs: BrowserTabInfo[];
  activeTabId: string | null;
  viewVisible: boolean;       // native view currently attached
  closedCount?: number;       // ⌘⇧T stack depth (additive; older renderers ignore)
  downloads?: DownloadInfo[]; // last 10, newest first (additive)
}

export interface DownloadInfo {
  id: string;
  filename: string;
  savePath: string;
  totalBytes: number;
  receivedBytes: number;
  state: 'progressing' | 'completed' | 'cancelled' | 'interrupted';
  startedAt: number;
}

export interface TopSite {
  url: string;
  title: string;
  visits: number;
  source: 'chrome' | 'cowork';
}

export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

// One interactive element from a DOM snapshot (bridge /snapshot). `index` is
// stable between a snapshot and a subsequent click/type because the page-side
// script stashes the element refs on window.__coworkBrowserEls.
export interface SnapshotEl {
  index: number;
  tag: string;
  role: string | null;
  text: string;
  href?: string;
  inputType?: string;
  bbox: { x: number; y: number; w: number; h: number };
}

export interface ChromeImportResult {
  imported: number;
  profiles: string[];
  error?: string;
}
