#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ASSETS_DIR="$ROOT_DIR/assets"
SVG="$ASSETS_DIR/icon.svg"
PNG="$ASSETS_DIR/icon.png"
ICONSET="$ASSETS_DIR/icon.iconset"
ICNS="$ASSETS_DIR/icon.icns"

if ! command -v qlmanage >/dev/null 2>&1; then
  echo "Error: qlmanage is required (macOS)." >&2
  exit 1
fi

if ! command -v sips >/dev/null 2>&1; then
  echo "Error: sips is required (macOS)." >&2
  exit 1
fi

if ! command -v iconutil >/dev/null 2>&1; then
  echo "Error: iconutil is required (macOS)." >&2
  exit 1
fi

if [[ ! -f "$SVG" ]]; then
  echo "Error: missing $SVG" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Rendering icon.svg -> icon.png"
qlmanage -t -s 1024 -o "$TMP_DIR" "$SVG" >/dev/null 2>&1 || {
  echo "Error: qlmanage could not render $SVG" >&2
  exit 1
}

if [[ -f "$TMP_DIR/icon.svg.png" ]]; then
  cp "$TMP_DIR/icon.svg.png" "$PNG"
elif [[ -f "$TMP_DIR/icon.png" ]]; then
  cp "$TMP_DIR/icon.png" "$PNG"
else
  echo "Error: rendered PNG was not generated by qlmanage." >&2
  exit 1
fi

# Remove white matte/halo pixels while preserving non-white content.
python3 - "$PNG" <<'PY'
import struct
import sys
import zlib

fn = sys.argv[1]
with open(fn, "rb") as f:
    sig = f.read(8)
    if sig != b"\x89PNG\r\n\x1a\n":
        raise SystemExit("Not a PNG")
    ihdr = None
    idat = b""
    while True:
        l = f.read(4)
        if not l:
            break
        n = int.from_bytes(l, "big")
        t = f.read(4)
        d = f.read(n)
        f.read(4)
        if t == b"IHDR":
            ihdr = d
            w = int.from_bytes(d[0:4], "big")
            h = int.from_bytes(d[4:8], "big")
            bit_depth = d[8]
            color_type = d[9]
            if bit_depth != 8 or color_type != 6:
                raise SystemExit("Expected 8-bit RGBA PNG")
        elif t == b"IDAT":
            idat += d
        elif t == b"IEND":
            break

raw = zlib.decompress(idat)
stride = w * 4
i = 0
prev = bytearray(stride)
rows = []

for _ in range(h):
    ftype = raw[i]
    i += 1
    row = bytearray(raw[i : i + stride])
    i += stride

    if ftype == 1:
        for x in range(stride):
            row[x] = (row[x] + (row[x - 4] if x >= 4 else 0)) & 0xFF
    elif ftype == 2:
        for x in range(stride):
            row[x] = (row[x] + prev[x]) & 0xFF
    elif ftype == 3:
        for x in range(stride):
            a = row[x - 4] if x >= 4 else 0
            b = prev[x]
            row[x] = (row[x] + ((a + b) // 2)) & 0xFF
    elif ftype == 4:
        def paeth(a, b, c):
            p = a + b - c
            pa = abs(p - a)
            pb = abs(p - b)
            pc = abs(p - c)
            if pa <= pb and pa <= pc:
                return a
            if pb <= pc:
                return b
            return c
        for x in range(stride):
            a = row[x - 4] if x >= 4 else 0
            b = prev[x]
            c = prev[x - 4] if x >= 4 else 0
            row[x] = (row[x] + paeth(a, b, c)) & 0xFF
    prev = row
    rows.append(row)

for row in rows:
    for x in range(0, stride, 4):
        r, g, b, a = row[x : x + 4]
        if a > 0 and r >= 245 and g >= 245 and b >= 245:
            row[x + 3] = 0

out = bytearray()
for row in rows:
    out.append(0)
    out.extend(row)

comp = zlib.compress(bytes(out), 9)

def chunk(t, d):
    return len(d).to_bytes(4, "big") + t + d + (zlib.crc32(t + d) & 0xFFFFFFFF).to_bytes(4, "big")

png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", comp) + chunk(b"IEND", b"")
with open(fn, "wb") as f:
    f.write(png)
PY

mkdir -p "$ICONSET"

echo "Generating icon.iconset"
sips -z 16 16 "$PNG" --out "$ICONSET/icon_16x16.png" >/dev/null
sips -z 32 32 "$PNG" --out "$ICONSET/icon_16x16@2x.png" >/dev/null
sips -z 32 32 "$PNG" --out "$ICONSET/icon_32x32.png" >/dev/null
sips -z 64 64 "$PNG" --out "$ICONSET/icon_32x32@2x.png" >/dev/null
sips -z 128 128 "$PNG" --out "$ICONSET/icon_128x128.png" >/dev/null
sips -z 256 256 "$PNG" --out "$ICONSET/icon_128x128@2x.png" >/dev/null
sips -z 256 256 "$PNG" --out "$ICONSET/icon_256x256.png" >/dev/null
sips -z 512 512 "$PNG" --out "$ICONSET/icon_256x256@2x.png" >/dev/null
sips -z 512 512 "$PNG" --out "$ICONSET/icon_512x512.png" >/dev/null
cp "$PNG" "$ICONSET/icon_512x512@2x.png"

echo "Generating icon.icns"
iconutil -c icns "$ICONSET" -o "$ICNS"

echo "Done:"
echo "  $PNG"
echo "  $ICONSET"
echo "  $ICNS"
